CONFIG_NAME: Fusion
dataset_name: face2text
data_dir: ./data/face2text
checkpoints_path: ./checkpoints

test_pair_list: ./data/face2text/images/test_199_sub.txt 
valid_pair_list: ./data/face2text/images/valid_199_sub.txt 

weights_adaface: "./weights/pretrained/adaface_ir18_webface4m.ckpt"
weights_arcface: "./weights/pretrained/arcface_ir18_ms1mv3.pth"

text_encoder_path: "./checkpoints/face2text/Train/BERT_arcface/bert/bert_text_encoder_18.pth"
image_encoder_path: "./checkpoints/face2text/Train/BERT_arcface/bert/arcface_image_encoder_18.pth"
resume_epoch: 1

# machine setup 
num_workers: 8 
gpu_id: [0]
manual_seed: 100
cuda: True

# model arch
img_size: 112
model_type: arcface #arcface, magface, adaface
ch_size: 3
backbone: resnet18
classify: softmax
num_classes: 4500 
metric: arc_margin 
easy_margin: False
loss: focal_loss 
optimizer: sgd 
use_se: False


# encoder settings
en_type: "BERT"   
bert_words_num: 24
captions_per_image: 4

bert_type: "bert" 
bert_config:  bert-base-uncased 
align_config: kakaobrain/align-base
clip_config: openai/clip-vit-base-patch32
blip_config: Salesforce/blip-image-captioning-base
falva_config: facebook/flava-full
groupvit_config: nvidia/groupvit-gcc-yfcc


# training settings 
lr_image_train: 0.1   #0.01 for ArcFace
lr_step: 5
gamma: 0.8  
weight_decay: 0.0005
lr_head: 0.001
temperature: 1.0

max_epoch: 36
batch_size: 16  
test_interval: 2
save_interval: 1
trainable: False


# fusion arch
fusion_type: fcfm #fcfm, linear, concat
fusion_final_dim: 640   
aux_feat_dim_per_granularity: 256

#save
roc_file: arc_face2text_roc
is_roc: False 
is_ident: False 

# flags
do_test: True