CONFIG_NAME: Fusion
dataset_name: face2text
data_dir: ./data/face2text
checkpoints_path: ./checkpoints

test_pair_list: ./data/face2text/images/test_299_sub.txt 
valid_pair_list: ./data/face2text/images/valid_199_sub.txt 

weights_adaface: "./weights/pretrained/adaface_ir18_webface4m.ckpt"
weights_arcface: "./weights/pretrained/arcface_ir18_ms1mv3.pth"
weights_magface: "./weights/pretrained/magface_iresnet18_casia_dp.pth"

text_encoder_path: "./checkpoints/face2text/Fusion/BERT_arcface/fcfm/encoder_BERT_fcfm_36.pth"
image_encoder_path: "./checkpoints/face2text/Fusion/BERT_arcface/fcfm/fusion_fcfm_arcface_36.pth"
fusion_net_path: "./checkpoints/face2text/Fusion/BERT_arcface/fcfm/fusion_fcfm_arcface_36.pth"
test_sub: 1193 #1217, 1193, 1617


# machine setup 
num_workers: 6 
gpu_id: [0]
manual_seed: 100
cuda: True
batch_size: 32


# model arch
img_size: 112
model_type: arcface #arcface, magface, arcface
ch_size: 3
backbone: resnet18
classify: softmax
num_classes: 4500 #8000, 4500 
metric: arc_margin 
easy_margin: False
loss: focal_loss 
optimizer: sgd 
use_se: False


# encoder settings
en_type: BERT        
lstm_words_num: 18 
embedding_dim: 256
bert_words_num: 24
captions_per_image: 4 #1, 4, 10 

bert_type: bert #bert 
bert_config:  bert-base-uncased #distilbert-base-uncased 
align_config: kakaobrain/align-base
clip_config: openai/clip-vit-base-patch32
blip_config: Salesforce/blip-image-captioning-base
falva_config: facebook/flava-full
groupvit_config: nvidia/groupvit-gcc-yfcc


# fusion arch
fusion_type: fcfm #fcfm, concat

fusion_final_dim: 640 
aux_feat_dim_per_granularity: 256

#save
roc_file: LSTM_arc_fcfm_face2text 
is_roc: True  
is_ident: True     

# flags
do_test: True